#!/data/data/com.termux/files/usr/bin/sh

set -u

if command -v kew-now-playing >/dev/null 2>&1 &&
    [ -n "$(kew-now-playing --peek 2>/dev/null)" ]; then
    tmux set-option -gq status 2
else
    tmux set-option -gq status on
fi

exit 0
