# termux-launcher theme sync: synthwave84 dark
foreground=#f8f8f2
background=#241b2f
cursor=#f97e72
color0=#241b2f
color1=#f97e72
color2=#72f1b8
color3=#fede5d
color4=#36f9f6
color5=#ff7edb
color6=#fede5d
color7=#ffffff
color8=#495495
color9=#f88414
color10=#72f1b8
color11=#fff951
color12=#36f9f6
color13=#ff7edb
color14=#f97e72
color15=#ffffff
