allow-external-apps = true

terminal-transcript-rows = 1000

volume-keys = volume

# fullscreen = true

### Cursor blink rate. Values 0, 100 - 2000.
terminal-cursor-blink-rate=600

### Cursor style: block, bar, underline.
terminal-cursor-style=bar

# Extra keys - two rows
# Top row: TUI app launchers (send prefix + key -> tmux bindings)
# Bottom row: Standard tmux controls
extra-keys = [[ \
  {macro: "CTRL b BKSP", display: "🔥"}, \
  {macro: "CTRL b TAB", display: "🕞"}, \
  {macro: "CTRL b ESC", display: "🎧"}, \
  {macro: "CTRL b ENTER", display: "📂"}, \
  {macro: "CTRL b DEL", display: "🌠"}, \
  {macro: "CTRL b PGUP", display: "📒"}, \
  {macro: "CTRL b PGDN", display: "🗓️"}, \
  {macro: "CTRL b END", display: "🔍"} \
], [ \
  {macro: "ALT z", display: "⇄"}, \
  {macro: "CTRL b -", display: "𝍣", popup: {macro: "CTRL b |", display: "𝍬"}}, \
  {macro: "CTRL b 1", display: "⓵"}, \
  {macro: "CTRL b 2", display: "⓶"}, \
  {macro: "CTRL b 3", display: "⓷"}, \
  {macro: "CTRL b [", display: "✎"}, \
  {key: PASTE, popup: KEYBOARD}, \
  {macro: "CTRL b", display: "㋡"} \
]]

### Force black colors for drawer and dialogs
use-black-ui=true

### Hide keyboard or leave app (default) or escape.
back-key=back

### Horizontal (left/right) Margin
terminal-margin-horizontal=0

### Vertical (top/bottom) Margin
terminal-margin-vertical=0
background-overlay-color=#82141218
